blank_issues_enabled: true
contact_links:
  - name: Device integration and issues
    url: https://dev.duboc.pro/homebridge-tahoma
    about: Start here for unsupported device or any command/state unexpected behaviour
