name: Create Release
on:
  issues:
    types: [opened]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Autoreply issue
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{github.event.issue.number}}
          comment-author: "dubocr"
          body: |
            Thank you for using Homebridge TaHoma plugin.

            If you think this could help resolve your issue, please:
            2. Report your config by browsing [https://dev.duboc.pro/homebridge-tahoma](https://dev.duboc.pro/homebridge-tahoma)
            4. Provide your gateway PIN number (last 4 digits of the number visible as SETUP-XXXX-XXXX-XXXX in step 2.)

            Thank you.
          token: ${{ secrets.GITHUB_TOKEN }}
