name: Mark stale issues and pull requests

on:
  schedule:
    - cron: "30 1 * * *"

jobs:
  stale:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/stale@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-issue-message: >
            'There hasn't been any activity on this issue recently.

            Please make sure to update to the latest Homebridge TaHoma version to see
            if that solves the issue.

            This issue will be closed in case of inactivity.'
          days-before-stale: 30
          days-before-close: 30
          stale-issue-label: "no-issue-activity"
          exempt-issue-labels: "blocked"
